// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase options for different platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for web platform
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWUTt39LOi9uuvngiRdNV7_790OYF7H0',
    appId: '1:473750465015:web:083dcc7edb466964b0a6f2',
    messagingSenderId: '473750465015',
    projectId: 'todolist-a20e7',
    authDomain: 'todolist-a20e7.firebaseapp.com',
    storageBucket: 'todolist-a20e7.firebasestorage.app',
    measurementId: 'G-0DMFHQTF33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAift9aDEQhj7PDPmrpvjrtIbWVeuDTJ8',
    appId: '1:336234675762:android:b3ec420ed0bac7016fc62b',
    messagingSenderId: '336234675762',
    projectId: 'bookswapapp-9d4fc',
    storageBucket: 'bookswapapp-9d4fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBysS-1hXuNP1RvrT3Q9iZLJymSpaLAKro',
    appId: '1:473750465015:ios:1e995d4a1037bd7bb0a6f2',
    messagingSenderId: '473750465015',
    projectId: 'todolist-a20e7',
    storageBucket: 'todolist-a20e7.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBysS-1hXuNP1RvrT3Q9iZLJymSpaLAKro',
    appId: '1:473750465015:ios:1e995d4a1037bd7bb0a6f2',
    messagingSenderId: '473750465015',
    projectId: 'todolist-a20e7',
    storageBucket: 'todolist-a20e7.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkWUTt39LOi9uuvngiRdNV7_790OYF7H0',
    appId: '1:473750465015:web:a0977182c6052891b0a6f2',
    messagingSenderId: '473750465015',
    projectId: 'todolist-a20e7',
    authDomain: 'todolist-a20e7.firebaseapp.com',
    storageBucket: 'todolist-a20e7.firebasestorage.app',
    measurementId: 'G-7GSZZH1YRD',
  );
}
