import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:book_swap_app/screens/verify_email_screen.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:book_swap_app/providers/auth_provider.dart';
import 'package:book_swap_app/screens/login_screen.dart';
import 'package:book_swap_app/screens/home_screen.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const ProviderScope(child: BookSwapApp()));
}

class BookSwapApp extends ConsumerWidget {
  const BookSwapApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStateChangesProvider);
    return MaterialApp(
      title: 'BookSwap',
      theme: ThemeData(primarySwatch: Colors.indigo, useMaterial3: true),
      home: authState.when(
        data: (user) {
          if (user == null) return const LoginScreen();
          if (!user.emailVerified) return const VerifyEmailScreen();
          return const HomeScreen();
        },
        loading: () =>
            const Scaffold(body: Center(child: CircularProgressIndicator())),
        error: (_, __) =>
            const Scaffold(body: Center(child: Text('Auth error'))),
      ),
    );
  }
}
